version: '2'
services:
    php-apache-environment:
        container_name: php-project
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - db
        ports:
            - 8888:80
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db            
            MYSQL_PASSWORD: root

    adminer-db:
        image: adminer
        ports:
            - '8887:8080'
        restart: always
        depends_on:
            - db
