
name: Docker Image CI

on:
  push:
    branches: [ "master" ]
      
jobs:
  docker_ci:
   runs-on: ubuntu-latest
   steps:    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: checkout
      uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:{{ github.sha }}

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:{{ github.sha }}
